### ISSUE TITLE
could not filter: if(

### ISSUE THREAD

**Issue by macjabeth** [batrick/lunadry#11]
I noticed that lunadry was not working on files that had that pattern **if(** so close together. I just switched them all so the ( had a space beforehand, and then it worked fine.

**Comment by bunster** [comment]
Also it could not filter functions that had a comma immediately following an ellipses (**,...**)

**Comment by bunster** [comment]
It also runs into errors when trying to parse files with luapp statements in them (lines starting with #).

**Comment by batrick** [comment]
I can't reproduce the `if(` problem:

```
$ echo 'if(true)then end' | lua lunadry.lua -
if true then
end
```

**Comment by batrick** [comment]
Nor this one:

```
$ echo 'print('hi',...)' | lua lunadry.lua -
print(hi, ...)
```

**Comment by batrick** [comment]
> It also runs into errors when trying to parse files with luapp statements in them (lines starting with #).

Please make separate issues from now. If you want to submit a PR that solves this without breaking existing programs, I will merge it.
