### ISSUE TITLE
allow something other than "lua" to execute lua.

### ISSUE THREAD

**Issue by client9** [batrick/lunadry#8]
Nice work

Not sure if you are still hacking on this or not, but..

The bash script should allow user-defined `lua` (either a different path, or perhaps `luajit`.. the naming schemes on various OS are screwy).

I'll work on a pull request.

n

**Comment by batrick** [comment]
Hi @client9, the bash script causes so many problems for people. The main reason for it is verification the source does not produce different bytecode. It should be possible to just get rid of it in favor of `io.popen` in lunadry.lua. If you want to cook that into a PR, I'd be happy to accept it.

**Comment by client9** [comment]
ahh yeah, I saw the other bash issue too.  Im sorta new to Lua, but I'll take a look at doing it in pure lua and work on a PR.
thanks!
